/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    DeliveryDate,
    DeliveryDateFromJSON,
    DeliveryDateToJSON,
    DeliveryDateDto,
    DeliveryDateDtoFromJSON,
    DeliveryDateDtoToJSON,
} from '../models';

export interface CreateDeliveryDateUsingPOSTRequest {
    deliveryDate: DeliveryDateDto;
}

export interface GetDeliveryDatesUsingGETRequest {
    page: number;
    size: number;
}

/**
 * no description
 */
export class DeliveryControllerApi extends runtime.BaseAPI {

    /**
     * createDeliveryDate
     */
    async createDeliveryDateUsingPOSTRaw(requestParameters: CreateDeliveryDateUsingPOSTRequest): Promise<runtime.ApiResponse<DeliveryDate>> {
        if (requestParameters.deliveryDate === null || requestParameters.deliveryDate === undefined) {
            throw new runtime.RequiredError('deliveryDate','Required parameter requestParameters.deliveryDate was null or undefined when calling createDeliveryDateUsingPOST.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/delivery`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeliveryDateDtoToJSON(requestParameters.deliveryDate),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => DeliveryDateFromJSON(jsonValue));
    }

    /**
     * createDeliveryDate
     */
    async createDeliveryDateUsingPOST(requestParameters: CreateDeliveryDateUsingPOSTRequest): Promise<DeliveryDate> {
        const response = await this.createDeliveryDateUsingPOSTRaw(requestParameters);
        return await response.value();
    }

    /**
     * getDeliveryDates
     */
    async getDeliveryDatesUsingGETRaw(requestParameters: GetDeliveryDatesUsingGETRequest): Promise<runtime.ApiResponse<Array<DeliveryDate>>> {
        if (requestParameters.page === null || requestParameters.page === undefined) {
            throw new runtime.RequiredError('page','Required parameter requestParameters.page was null or undefined when calling getDeliveryDatesUsingGET.');
        }

        if (requestParameters.size === null || requestParameters.size === undefined) {
            throw new runtime.RequiredError('size','Required parameter requestParameters.size was null or undefined when calling getDeliveryDatesUsingGET.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/delivery`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DeliveryDateFromJSON));
    }

    /**
     * getDeliveryDates
     */
    async getDeliveryDatesUsingGET(requestParameters: GetDeliveryDatesUsingGETRequest): Promise<Array<DeliveryDate>> {
        const response = await this.getDeliveryDatesUsingGETRaw(requestParameters);
        return await response.value();
    }

}
