/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    addressLineOne?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    addressLineTwo?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    billing?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    country?: string;
    /**
     * 
     * @type {number}
     * @memberof Address
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    postalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    province?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    shipping?: boolean;
}

export function AddressFromJSON(json: any): Address {
    return AddressFromJSONTyped(json, false);
}

export function AddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): Address {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addressLineOne': !exists(json, 'addressLineOne') ? undefined : json['addressLineOne'],
        'addressLineTwo': !exists(json, 'addressLineTwo') ? undefined : json['addressLineTwo'],
        'billing': !exists(json, 'billing') ? undefined : json['billing'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'postalCode': !exists(json, 'postalCode') ? undefined : json['postalCode'],
        'province': !exists(json, 'province') ? undefined : json['province'],
        'shipping': !exists(json, 'shipping') ? undefined : json['shipping'],
    };
}

export function AddressToJSON(value?: Address | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addressLineOne': value.addressLineOne,
        'addressLineTwo': value.addressLineTwo,
        'billing': value.billing,
        'city': value.city,
        'country': value.country,
        'id': value.id,
        'postalCode': value.postalCode,
        'province': value.province,
        'shipping': value.shipping,
    };
}


