/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AddressDto,
    AddressDtoFromJSON,
    AddressDtoFromJSONTyped,
    AddressDtoToJSON,
    UserDto,
    UserDtoFromJSON,
    UserDtoFromJSONTyped,
    UserDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface OrderDto
 */
export interface OrderDto {
    /**
     * 
     * @type {AddressDto}
     * @memberof OrderDto
     */
    address: AddressDto;
    /**
     * 
     * @type {Date}
     * @memberof OrderDto
     */
    deliveryDate: Date;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    deliveryType: OrderDtoDeliveryTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof OrderDto
     */
    paymentType: OrderDtoPaymentTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof OrderDto
     */
    quantity: number;
    /**
     * 
     * @type {UserDto}
     * @memberof OrderDto
     */
    user: UserDto;
}

export function OrderDtoFromJSON(json: any): OrderDto {
    return OrderDtoFromJSONTyped(json, false);
}

export function OrderDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': AddressDtoFromJSON(json['address']),
        'deliveryDate': (new Date(json['deliveryDate'])),
        'deliveryType': json['deliveryType'],
        'paymentType': json['paymentType'],
        'quantity': json['quantity'],
        'user': UserDtoFromJSON(json['user']),
    };
}

export function OrderDtoToJSON(value?: OrderDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': AddressDtoToJSON(value.address),
        'deliveryDate': (value.deliveryDate.toISOString()),
        'deliveryType': value.deliveryType,
        'paymentType': value.paymentType,
        'quantity': value.quantity,
        'user': UserDtoToJSON(value.user),
    };
}

/**
* @export
* @enum {string}
*/
export enum OrderDtoDeliveryTypeEnum {
    DELIVER = 'DELIVER',
    PICKUP = 'PICK_UP',
    MEETUP = 'MEET_UP'
}
/**
* @export
* @enum {string}
*/
export enum OrderDtoPaymentTypeEnum {
    CASH = 'CASH',
    GCASH = 'GCASH'
}


